In [85]:
#сортировка по HEATID

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#import collections as col

pdRec = pd.read_csv('Recipes.csv', header = 0)
pdDef = pd.read_csv('Defects.csv', header = 0)

pdRec.sort_values(['HEATID'],ascending=True,axis=0,inplace=True,na_position='last')
pdDef.sort_values(['HEAT_ID'],ascending=True,axis=0,inplace=True,na_position='last')

pdRec.to_csv(r'Recipes_sort.csv',index=None,header=True)
pdDef.to_csv(r'Defects_sort.csv',index=None,header=True)

pdRec.head(10)


#Rec=pdRec.to_numpy()[:,[0,1,3]] #HEAT_ID     MATERIAL_CODE    WEIGHT 
#Def=pdDef.to_numpy()[:,0:3]     #PIECE_ID    HEAT_ID          DEFECT_TYPE

#Sorted of HEAT_ID_NUMPY

#order = Rec[:, 0].argsort()
#Rec = np.take(Rec, order, 0)

#order = Def[:, 1].argsort()
#Def = np.take(Def, order, 0)

#openfile = 'Recipes2'
#np.save(openfile,Rec)

HEATID  Material_Code                NAME    WEIGHT
0   1701190            112      # 2 HEAVY MELT  158758.0
1   1701192            113            PIG IRON   50306.6
2   1701192            115          HOME SCRAP    2215.8
3   1701192            114           PIT SCRAP    3473.6
12  1701194            120     RAILROAD WHEELS    2180.0
11  1701194            124          #1 BUNDLES    9100.0
10  1701194            126        #1 BUSHELING   42110.7
9   1701194            114           PIT SCRAP    3426.0
8   1701194            121  PLATE & STRUCTURAL   13200.9
7   1701194            115          HOME SCRAP    2322.8

In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pdRec = pd.read_csv('Recipes_sort.csv', header = 0)
#pdDef = pd.read_csv('Defects_sort.csv', header = 0)
Rec=pdRec.to_numpy()
#HEATID,Material_Code,NAME,WEIGHT
#Def=pdDef.to_numpy()
#PIECE_ID,HEAT_ID,DEFECT_TYPE,DEFECT_NAME,DEFECT_GROUP_ID,DEFECT_GROUP_Name

#удаляем лишние строки(дубликаты) для одной и той же плавки
heat=list(Rec[:,0])
m_code=list(Rec[:,1])
weight=list(Rec[:,3])
l=len(heat)

tl=[]#код материала для текущей плавки
ti=[]#индекс для tl
tl.append(m_code[l-1])
ti.append(l-1)

for i in reversed(range(l-1)):
    if(heat[i]!=heat[i+1]):
        tl.clear()#сбрасываем при новой плавке
        ti.clear()
    else:    
        if (m_code[i] in tl):#если это одна и та же плавка, и код разных материалов вдруг совпадает
            print("Удаляем строку",i,"плавки",heat[i],"код материала",m_code[i])
            j=tl.index(m_code[i])#находим номер строки, которая уже записана была. i-я строка записана не будет
            j=ti[j]#достаем номер строки
            Rec[j,3]=weight[i]+weight[j]
            print("Удаляемая строка:",i,"совпала",j,"удалить",weight[i],"был вес",weight[j],"стал вес:",Rec[j,3])
            Rec=np.delete(Rec,(i),axis=0)
        else:     #код материалов не совпадает. Добавляем этот код тоже       
            tl.append(m_code[i])
            ti.append(i)

#Вывод максимального числа осей в одной плавке
heat=list(Rec[:,0])
m_code=list(Rec[:,1])
weight=list(Rec[:,3])
l=len(heat)

maxax=heat.count(heat[l-1])
imax=l-1
for i in reversed(range(l-1)):
    if(heat[i]!=heat[i+1]):    
        temp=heat.count(heat[i])
        if(temp>maxax):
            maxax=temp
            imax=i           
    heat.pop()
print("Максимальное число осей для одной плавки: ",maxax)

#Вывод материалов с maxax
heat=list(Rec[:,0])
maxheat=heat[imax]

found = maxheat in heat
while(found):
    p=heat.index(maxheat)
    print("Номер строки и код материала maxax",maxheat,p,Rec[p,1])
    heat[p]=0
    found = maxheat in heat  

#поиск общего количества осей во всех HEATID
m_code=list(Rec[:,1])
ta=[]#список кодов отличающихся материалов
l=len(m_code)

for i in reversed(range(l)):
    temp=m_code[i]
    m_code.pop()
    found= temp in m_code
    if (found==False):
        ta.append(temp)
print("Максимальное число осей: ",len(ta),"коды материалов: ",ta)
    
pdRec=pd.DataFrame(Rec,index=None,columns=['HEATID','Material_Code','NAME','WEIGHT'])
pdRec.to_csv(r'Recipes_del.csv',index=None,header=True)

pdRec.head(10)

Удаляем строку 99928 плавки 1811188 код материала 117
Удаляемая строка: 99928 совпала 99930 удалить 50983.8 был вес 51528.2 стал вес: 102512.0
Удаляем строку 99927 плавки 1811188 код материала 119
Удаляемая строка: 99927 совпала 99929 удалить 6346.2 был вес 6479.1 стал вес: 12825.3
Удаляем строку 99924 плавки 1811188 код материала 126
Удаляемая строка: 99924 совпала 99926 удалить 11012.8 был вес 10716.1 стал вес: 21728.9
Удаляем строку 99921 плавки 1811188 код материала 121
Удаляемая строка: 99921 совпала 99922 удалить 21544.3 был вес 21676.8 стал вес: 43221.1
Удаляем строку 99918 плавки 1811188 код материала 181
Удаляемая строка: 99918 совпала 99919 удалить 10952.0 был вес 10948.8 стал вес: 21900.8
Удаляем строку 99917 плавки 1811188 код материала 124
Удаляемая строка: 99917 совпала 99923 удалить 4734.6 был вес 4544.1 стал вес: 9278.7
Удаляем строку 99916 плавки 1811188 код материала 208
Удаляемая строка: 99916 совпала 99920 удалить 32923.1 был вес 33255.2 стал вес: 66178.29999999999


Удаляем строку 91206 плавки 1808970 код материала 113
Удаляемая строка: 91206 совпала 91207 удалить 22940.9 был вес 27483.2 стал вес: 50424.100000000006
Удаляем строку 91203 плавки 1808970 код материала 117
Удаляемая строка: 91203 совпала 91205 удалить 12873.9 был вес 22686.0 стал вес: 35559.9
Удаляем строку 91201 плавки 1808970 код материала 126
Удаляемая строка: 91201 совпала 91202 удалить 40791.2 был вес 59319.1 стал вес: 100110.29999999999
Удаляем строку 91200 плавки 1808970 код материала 126
Удаляемая строка: 91200 совпала 91202 удалить 45491.7 был вес 59319.1 стал вес: 104810.79999999999
Удаляем строку 90971 плавки 1808896 код материала 113
Удаляемая строка: 90971 совпала 90972 удалить 34998.8 был вес 35500.4 стал вес: 70499.20000000001
Удаляем строку 90970 плавки 1808896 код материала 117
Удаляемая строка: 90970 совпала 90975 удалить 34790.6 был вес 35158.0 стал вес: 69948.6
Удаляем строку 90969 плавки 1808896 код материала 126
Удаляемая строка: 90969 совпала 90973 удалить 28504

Удаляем строку 81530 плавки 1806548 код материала 113
Удаляемая строка: 81530 совпала 81531 удалить 30932.3 был вес 31071.1 стал вес: 62003.399999999994
Удаляем строку 81525 плавки 1806548 код материала 121
Удаляемая строка: 81525 совпала 81528 удалить 10634.0 был вес 10742.9 стал вес: 21376.9
Удаляем строку 81524 плавки 1806548 код материала 211
Удаляемая строка: 81524 совпала 81527 удалить 4565.4 был вес 4663.8 стал вес: 9229.2
Удаляем строку 81523 плавки 1806548 код материала 117
Удаляемая строка: 81523 совпала 81526 удалить 60539.7 был вес 60509.3 стал вес: 121049.0
Удаляем строку 81521 плавки 1806548 код материала 126
Удаляемая строка: 81521 совпала 81522 удалить 19996.2 был вес 19006.5 стал вес: 39002.7
Удаляем строку 81519 плавки 1806548 код материала 166
Удаляемая строка: 81519 совпала 81520 удалить 21387.8 был вес 21776.1 стал вес: 43163.899999999994
Удаляем строку 81338 плавки 1806500 код материала 115
Удаляемая строка: 81338 совпала 81341 удалить 11138.9 был вес 11136.6 стал

Удаляемая строка: 65031 совпала 65032 удалить 9143.1 был вес 27460.5 стал вес: 36603.6
Удаляем строку 64532 плавки 1801836 код материала 117
Удаляемая строка: 64532 совпала 64533 удалить 9011.5 был вес 27833.4 стал вес: 36844.9
Удаляем строку 64528 плавки 1801836 код материала 113
Удаляемая строка: 64528 совпала 64529 удалить 9147.6 был вес 51836.1 стал вес: 60983.7
Удаляем строку 63982 плавки 1801620 код материала 117
Удаляемая строка: 63982 совпала 63983 удалить 9413.4 был вес 42048.1 стал вес: 51461.5
Удаляем строку 63981 плавки 1801620 код материала 126
Удаляемая строка: 63981 совпала 63984 удалить 19026.0 был вес 39306.5 стал вес: 58332.5
Удаляем строку 63386 плавки 1801424 код материала 126
Удаляемая строка: 63386 совпала 63387 удалить 18184.1 был вес 36265.2 стал вес: 54449.299999999996
Удаляем строку 62583 плавки 1801200 код материала 113
Удаляемая строка: 62583 совпала 62585 удалить 22726.8 был вес 18155.5 стал вес: 40882.3
Удаляем строку 62581 плавки 1801200 код материала 113

Удаляем строку 38172 плавки 1711858 код материала 117
Удаляемая строка: 38172 совпала 38175 удалить 43332.2 был вес 43332.2 стал вес: 86664.4
Удаляем строку 38171 плавки 1711858 код материала 113
Удаляемая строка: 38171 совпала 38176 удалить 30736.8 был вес 30736.8 стал вес: 61473.6
Удаляем строку 38100 плавки 1711832 код материала 117
Удаляемая строка: 38100 совпала 38101 удалить 9078.2 был вес 9856.6 стал вес: 18934.800000000003
Удаляем строку 38094 плавки 1711832 код материала 113
Удаляемая строка: 38094 совпала 38098 удалить 38764.5 был вес 9005.2 стал вес: 47769.7
Удаляем строку 38093 плавки 1711832 код материала 126
Удаляемая строка: 38093 совпала 38096 удалить 67180.3 был вес 18158.7 стал вес: 85339.0
Удаляем строку 36404 плавки 1711346 код материала 113
Удаляемая строка: 36404 совпала 36405 удалить 31752.0 был вес 31691.6 стал вес: 63443.6
Удаляем строку 36401 плавки 1711346 код материала 117
Удаляемая строка: 36401 совпала 36403 удалить 8001.4 был вес 7966.0 стал вес: 15967.4


Удаляем строку 7644 плавки 1703476 код материала 113
Удаляемая строка: 7644 совпала 7646 удалить 27671.0 был вес 27744.0 стал вес: 55415.0
Удаляем строку 7642 плавки 1703476 код материала 124
Удаляемая строка: 7642 совпала 7643 удалить 8954.8 был вес 8930.8 стал вес: 17885.6
Удаляем строку 7641 плавки 1703476 код материала 121
Удаляемая строка: 7641 совпала 7649 удалить 9027.9 был вес 9057.8 стал вес: 18085.699999999997
Удаляем строку 7639 плавки 1703476 код материала 166
Удаляемая строка: 7639 совпала 7645 удалить 12604.0 был вес 9518.2 стал вес: 22122.2
Удаляем строку 7638 плавки 1703476 код материала 120
Удаляемая строка: 7638 совпала 7640 удалить 6994.9 был вес 7028.9 стал вес: 14023.8
Удаляем строку 7419 плавки 1703418 код материала 126
Удаляемая строка: 7419 совпала 7420 удалить 46442.9 был вес 54344.1 стал вес: 100787.0
Удаляем строку 7417 плавки 1703418 код материала 114
Удаляемая строка: 7417 совпала 7418 удалить 2254.8 был вес 1990.8 стал вес: 4245.6
Удаляем строку 7414 плавк

HEATID Material_Code                NAME   WEIGHT
0  1701190           112      # 2 HEAVY MELT   158758
1  1701192           113            PIG IRON  50306.6
2  1701192           115          HOME SCRAP   2215.8
3  1701192           114           PIT SCRAP   3473.6
4  1701194           120     RAILROAD WHEELS     2180
5  1701194           124          #1 BUNDLES     9100
6  1701194           126        #1 BUSHELING  42110.7
7  1701194           114           PIT SCRAP     3426
8  1701194           121  PLATE & STRUCTURAL  13200.9
9  1701194           115          HOME SCRAP   2322.8

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pdRec = pd.read_csv('Recipes_del.csv', header = 0)
Rec=pdRec.to_numpy()

#вычисление процентного соотношения материалов Recipes_p
heat=list(Rec[:,0])
weight=list(Rec[:,3])
dens=[]
l=len(heat)

tl=[]#вес для текущей плавки
tl.append(weight[l-1])

for i in reversed(range(l-1)):
    if(heat[i]!=heat[i+1]):
        temp=np.sum(tl)
        for j in range(len(tl)):
            tl[j]=round(((tl[j]/temp)*100),2)
        dens.extend(tl)
        #print("Сумма для",heat[i+1],":",temp)
        tl.clear()#сбрасываем при новой плавке
    tl.append(weight[i])
temp=np.sum(tl)
for j in range(len(tl)):
    tl[j]=(tl[j]/temp)*100
dens.extend(tl)
dens.reverse()
dena=np.array(dens)
dena=np.reshape(dena,(len(dens),1))
#print(dena.shape)
#print(Rec.shape)

Rec=np.hstack((Rec,dena)) 

pdRec=pd.DataFrame(Rec,index=None,columns=['HEATID','Material_Code','NAME','WEIGHT','PROCENT'])
pdRec.to_csv(r'Recipes_p.csv',index=None,header=True)
print(Rec)

[[1701190 112 '# 2 HEAVY MELT' 158758.0 100.0]
 [1701192 113 'PIG IRON' 50306.6 89.84]
 [1701192 115 'HOME SCRAP' 2215.8 3.96]
 ...
 [1811206 181 'PICKLE CLIPS' 10033.0 6.59]
 [1811206 121 'PLATE & STRUCTURAL' 21178.3 13.92]
 [1811206 119 'RAIL CROPS' 6534.9 4.29]]


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pdRec = pd.read_csv('Recipes_p.csv', header = 0)
Rec=pdRec.to_numpy()
print(Rec.shape)

#30 измерений для материалов - в каждой координате записано значение плотности m
#одномерный массив наличия дефектов def


(99531, 5)


In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#удаляем дубликаты из defects
pdDef = pd.read_csv('Defects.csv', header = 0)

pdDef.sort_values(['HEAT_ID'],ascending=True,axis=0,inplace=True,na_position='last')

Def=pdDef.to_numpy()

Def1=Def[:,[0,1,2]]
new_arr1 = [tuple(row) for row in Def1]
uniques,index = np.unique(new_arr1,return_index=True,axis=0)

uni2=np.empty((uniques.shape[0],Def.shape[1]),dtype=object)

print(uniques.shape)
print(Def.shape)
print(index.shape)
print(uniques)

for i in range(uniques.shape[0]):
    for j in range(Def.shape[1]):
        uni2[i,j]=Def[index[i],j]
print(uni2)    

#for i in range(len(index))

#Def2=Def[:,[3,4,5]]
#arr1 = new_arr1
#arr2 = [tuple(row) for row in Def2]
#arr3 = np.hstack((arr1,arr2))

#for i in range(uniques.shape[0]):
#    for j in range(arr3.shape[0]):
#        if(uniques[i]==arr3[j,0]):
#            uni2[i,0]=arr3[j,0]
#            uni2[i,1]=arr3[j,1]
#            break

#print(new_arr1)


pdDef=pd.DataFrame(uni2,index=None,columns=['PIECE_ID','HEAT_ID','DEFECT_TYPE','DEFECT_NAME','DEFECT_GROUP_ID','DEFECT_GROUP_Name'])
pdDef.sort_values(['HEAT_ID'],ascending=True,axis=0,inplace=True,na_position='last')

pdDef.to_csv(r'Defects_sort.csv',index=None,header=True)

pdDef.head(10)


(465201, 3)
(563048, 6)
(465201,)
[[ 166934 1701358      89]
 [ 166934 1701358      90]
 [ 166934 1701358     150]
 ...
 [ 679818 1808140     182]
 [ 679818 1808140     211]
 [ 679818 1808140     216]]
[[166934 1701358 89 'Profile: Crown' 'SH' '2-Shape']
 [166934 1701358 90 'Profile: Wedge' 'SH' '2-Shape']
 [166934 1701358 150 'Under Weight' 'DM' '3-Dimension']
 ...
 [679818 1808140 182 'pending PQA results' 'OTH' '0-Other']
 [679818 1808140 211 'Off Chemistry' 'MET' '9-Metallurgy']
 [679818 1808140 216 'Bad Dimensions on Calculated Weight' 'OTH'
  '0-Other']]


PIECE_ID  HEAT_ID DEFECT_TYPE                           DEFECT_NAME  \
62   167869  1701192         190  Wait For Weight - No L2 Scale Weight   
70   167870  1701192         169                Wrong Cooling Strategy   
69   167870  1701192         168               Coiling Temperature Low   
68   167870  1701192         167              Coiling Temperature High   
67   167870  1701192         150                          Under Weight   
66   167870  1701192         149                           Under Gauge   
65   167870  1701192         148                            Over Width   
64   167870  1701192         146                            Over Gauge   
63   167870  1701192          89                        Profile: Crown   
61   167869  1701192         182                   pending PQA results   

   DEFECT_GROUP_ID DEFECT_GROUP_Name  
62              DM       3-Dimension  
70             OTH           0-Other  
69             OTH           0-Other  
68             OTH           0-Other  
67              DM       3-Dimension  
66              DM       3-Dimension  
65              DM       3-Dimension  
64              DM       3-Dimension  
63              SH           2-Shape  
61             OTH           0-Other